### ISSUE TITLE
Release for PHP 8.4

### ISSUE THREAD

**Issue by srjlewis** [maxmind/web-service-common-php#56]
Could there be a release so the fixes for PHP 8.4 can be used without having to use dev-main in compser

**Comment by oschwald** [comment]
Sorry, could you expand a bit on the error you are receiving with 8.4? I am only seeing style changes between 0.9.0 and `main`. I'd expect them to work equally well on 8.4

**Comment by srjlewis** [comment]
Yes PHP 8.4 a derecated implicitly nullable parameter types

RFC: Deprecate implicitly nullable parameter types
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

Fixed in commit https://github.com/maxmind/web-service-common-php/commit/f33ce5bef4ba50b6c5d2cdd33e6ecf81e4af7908

**Comment by oschwald** [comment]
Ah, I see. Thanks for clarifying. We can do a release.

**Comment by oschwald** [comment]
This was done.
